"""Regression lock for the v1 reference case.

This test guarantees that future refactors of ``cabletract.simulate.run_single``
do not silently change the headline numbers that the v1 manuscript scaffold
already cites. It loads the checked-in ``reference_case.csv`` (generated by
the original ``compute_reference_case`` function) and asserts that every
field is reproduced to 6 significant figures.

Run with either pytest or as a standalone script:

    python tests/test_simulate.py
    pytest tests/test_simulate.py
"""

from __future__ import annotations

import math
import sys
from dataclasses import asdict
from pathlib import Path

import pandas as pd

# Allow `python tests/test_simulate.py` execution from anywhere by adding the
# package root to sys.path. pytest does not need this but the standalone path
# does.
ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from cabletract import CableTractParams, run_single  # noqa: E402

REFERENCE_CSV = ROOT / "reference_case.csv"
SIG_FIGS = 6


def _approx_equal(a: float, b: float, sig_figs: int = SIG_FIGS) -> bool:
    """Compare two floats to a given number of significant figures."""
    if a == b:
        return True
    if math.isnan(a) and math.isnan(b):
        return True
    scale = max(abs(a), abs(b))
    if scale == 0.0:
        return True
    rel_tol = 10.0 ** (-sig_figs)
    return abs(a - b) / scale < rel_tol


def test_reference_case_matches_csv() -> None:
    assert REFERENCE_CSV.exists(), (
        f"reference CSV not found at {REFERENCE_CSV}; cannot lock regression"
    )
    expected = pd.read_csv(REFERENCE_CSV, index_col=0)["value"]
    actual = run_single(CableTractParams())
    actual_dict = asdict(actual)

    mismatches = []
    for field, expected_str in expected.items():
        if field not in actual_dict:
            mismatches.append(f"missing field in Results: {field}")
            continue
        actual_val = actual_dict[field]
        # battery_sufficient is a bool, encoded as "True"/"False" in the CSV
        if isinstance(actual_val, bool):
            expected_bool = str(expected_str).strip().lower() in ("true", "1", "1.0")
            if actual_val != expected_bool:
                mismatches.append(
                    f"{field}: expected {expected_bool}, got {actual_val}"
                )
            continue
        try:
            expected_val = float(expected_str)
        except (TypeError, ValueError):
            mismatches.append(f"{field}: cannot parse expected value '{expected_str}'")
            continue
        if not _approx_equal(actual_val, expected_val):
            mismatches.append(
                f"{field}: expected {expected_val!r}, got {actual_val!r}"
            )

    assert not mismatches, "Reference case regression failures:\n  " + "\n  ".join(
        mismatches
    )


def test_results_field_count_matches_csv() -> None:
    expected = pd.read_csv(REFERENCE_CSV, index_col=0)["value"]
    actual = run_single(CableTractParams())
    actual_keys = set(asdict(actual).keys())
    expected_keys = set(expected.index)
    missing = expected_keys - actual_keys
    extra = actual_keys - expected_keys
    assert not missing, f"Results is missing fields present in legacy CSV: {missing}"
    assert not extra, f"Results has new fields not present in legacy CSV: {extra}"


if __name__ == "__main__":
    test_reference_case_matches_csv()
    test_results_field_count_matches_csv()
    print("ok: cabletract.simulate.run_single reproduces reference_case.csv to 6 sig figs")
